name: greetings

on:
  push:
    paths:
      - 'src/main/js/**/*.js'  # This will trigger the action when any .js file is committed

jobs:
  bump-version:
    if: contains(github.event.head_commit.message, '[bump-version]')
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Grants permission to push changes
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0  # Correct indentation under 'with'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Run bump version script
        run: node scripts/bumpJsVersion.js

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the automatically provided GitHub token
        run: |
          git config user.name 'kushpandya'
          git config user.email 'kushpandya@vasyerp.com'
          git add .
          git commit -m "Bumped JS version in JSP files"
          git push
        continue-on-error: true
